apiVersion: v1
kind: Service
metadata:
  name: ai-test-service
spec:
  selector:
    app: ai-test
  ports:
    - protocol: "TCP"
      port: 6401
      targetPort: 5401
      nodePort: 35401
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-test
spec:
  selector:
    matchLabels:
      app: ai-test
  replicas: 1
  template:
    metadata:
      labels:
        app: ai-test
    spec:
      containers:
        - name: ai-test
          image: sehooh5/ai-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5401
