FROM python:3.8

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        cmake \
        git \
        wget \
        unzip \
        yasm \
        pkg-config \
        libswscale-dev \
        libtbb2 \
        libtbb-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libavformat-dev \
        libpq-dev \
        vlc \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i 's/geteuid/getppid/' /usr/bin/vlc

VOLUME ["/home/$USER"]
VOLUME ["/etc/passwd"]
VOLUME ["/tmp/.X11-unix"]
VOLUME ["/dev/dri"]
ENV DISPLAY=unix$DISPLAY
USER 1000

RUN mkdir /app
WORKDIR /app
ADD . /app/
RUN pip3 install -r requirements.txt
RUN ln -s \
  /usr/local/python/cv2/python-3.8/cv2.cpython-37m-x86_64-linux-gnu.so \
  /usr/local/lib/python3.8/site-packages/cv2.so


EXPOSE 5401
CMD ["python3", "/app/main.py"]