
apiVersion: v1
kind: Service
metadata:
  name: select-cam-keti1-worker1-service
spec:
  selector:
    app: select-cam-keti1-worker1
  ports:
    - protocol: "TCP"
      port: 6807
      targetPort: 5050
      nodePort: 31343
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: select-cam-keti1-worker1
spec:
  selector:
    matchLabels:
      app: select-cam-keti1-worker1
  template:
    metadata:
      labels:
        app: select-cam-keti1-worker1
    spec:
      nodeName: keti1-worker1
      containers:
        - name: select-cam-keti1-worker1
          image: sehooh5/select-cam:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050