apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherai
  template:
    metadata:
      labels:
        app: weatherai
    spec:
      nodeName: intellivix-worker-01
      containers:
        - name: weatherai
          image: 192.168.0.4:5000/weatherai-00:01
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name : regcred