apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoringr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoringr
  template:
    metadata:
      labels:
        app: monitoringr
    spec:
      nodeName: intellivix-worker-01
      containers:
        - name: monitoringr
          image: 192.168.0.4:5000/monitoringr:01
          imagePullPolicy: Always
          ports:
            - containerPort: 8061
      imagePullSecrets:
      - name : regcred