apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherai
  template:
    metadata:
      labels:
        app: weatherai
    spec:
      nodeName: intellivix-desktop
      containers:
      - name: weatherai
        image: 192.168.0.15:5000/weatherai-00:01
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred