
apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  selector:
    app: content
  ports:
    - protocol: "TCP"
      port: 6505
      targetPort: 5917
      nodePort: 32758
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
spec:
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      nodeName: test-워커2
      containers:
        - name: content
          image: sehooh5/content:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5917