apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-01
  template:
    metadata:
      labels:
        app: monitoring-01
    spec:
      nodeName: intellivix-desktop
      containers:
        - name: monitoring-01
          image: 192.168.0.15:5000/monitoring-01:01
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name : regcred