apiVersion: v1
kind: Service
metadata:
  name: manager-service
spec:
  selector:
    app: manager
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
      nodePort: 30000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      nodeName: keti1-worker1
      containers:
        - name: manager
          image: sehooh5/manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
