apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitorings
  namespace: keti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitorings
  template:
    metadata:
      labels:
        app: monitorings
    spec:
      containers:
        - name: monitorings
          image: monitorings:01
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
      imagePullSecrets:
      - name : regcred