apiVersion: v1
kind: Service
metadata:
  name: flask-opencv-service
spec:
  selector:
    app: flask-opencv
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-opencv
spec:
  selector:
    matchLabels:
      app: flask-opencv
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-opencv
    spec:
      containers:
        - name: flask-opencv
          image: sehooh5/flask-opencv2:latest
          imagePullPolicy: Always
          command: ["sh", "-c", "echo xxx && sleep 6000"]
          ports:
            - containerPort: 5000
